/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YsLzk8dCRaj
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"

export function Home() {
  return <>
    <div className="grid md:grid-cols-2 gap-8 items-center">
      <div className="space-y-4">
        <h1 className="text-4xl font-bold">Record and Transcribe</h1>
        <p className="text-muted-foreground">
          Capture your ideas and conversations with our powerful audio recording and transcription tool.
        </p>
        <Button size="lg" className="w-full md:w-auto" asChild>
          <Link href="/recordings/new">
            <MicIcon className="w-5 h-5 mr-2" />
            Start Recording
          </Link>
        </Button>
      </div>
      <div className="relative w-full aspect-square max-w-[400px] mx-auto">
        <div className="absolute inset-0 flex items-center justify-center">
          <div className="size-[200px] rounded-full flex items-center justify-center bg-primary/10 animate-pulse" >
            <MicIcon className="w-20 h-20 text-primary" />
          </div>
        </div>
      </div>
    </div>
    <div className="mt-12 md:mt-24 space-y-8">
      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-bold">Recent Recordings</h2>
        <Link href="/recordings" className="text-primary hover:underline">
          View All
        </Link>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        <Card>
          <CardHeader>
            <CardTitle>Meeting Notes</CardTitle>
            <CardDescription>June 15, 2023</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="text-muted-foreground">
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nisl nec ultricies lacus, nisl
                nec ultricies lacus.
              </p>
            </div>
          </CardContent>
          <CardFooter>
            <Button variant="ghost" size="icon">
              <div className="w-5 h-5" />
            </Button>
            <Button variant="ghost" size="icon">
              <div className="w-5 h-5" />
            </Button>
          </CardFooter>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Interview Transcript</CardTitle>
            <CardDescription>June 10, 2023</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="text-muted-foreground">
              <p>
                Sed euismod, nisl nec ultricies lacus, nisl nec ultricies lacus. Lorem ipsum dolor sit amet,
                consectetur adipiscing elit.
              </p>
            </div>
          </CardContent>
          <CardFooter>
            <Button variant="ghost" size="icon">
              <div className="w-5 h-5" />
            </Button>
            <Button variant="ghost" size="icon">
              <div className="w-5 h-5" />
            </Button>
          </CardFooter>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Brainstorming Session</CardTitle>
            <CardDescription>June 5, 2023</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="text-muted-foreground">
              <p>
                Nisl nec ultricies lacus, nisl nec ultricies lacus. Lorem ipsum dolor sit amet, consectetur
                adipiscing elit. Sed euismod.
              </p>
            </div>
          </CardContent>
          <CardFooter>
            <Button variant="ghost" size="icon">
              <div className="w-5 h-5" />
            </Button>
            <Button variant="ghost" size="icon">
              <div className="w-5 h-5" />
            </Button>
          </CardFooter>
        </Card>
      </div>
    </div>
  </>
}

function MicIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z" />
      <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
      <line x1="12" x2="12" y1="19" y2="22" />
    </svg>
  )
}
