/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YsLzk8dCRaj
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Suspense } from "react"
import { api } from "@/trpc/server"

export function Home() {
  return <>
    <div className="grid md:grid-cols-2 gap-8 items-center">
      <div className="space-y-4">
        <h1 className="text-4xl font-bold">Record and Transcribe</h1>
        <p className="text-muted-foreground">
          Capture your ideas and conversations with our powerful audio recording and transcription tool.
        </p>
        <Button size="lg" className="w-full md:w-auto" asChild>
          <Link href="/recordings/new">
            <MicIcon className="w-5 h-5 mr-2" />
            Start Recording
          </Link>
        </Button>
      </div>
      <div className="relative w-full aspect-square max-w-[400px] mx-auto">
        <div className="absolute inset-0 flex items-center justify-center">
          <div className="size-[200px] rounded-full flex items-center justify-center bg-primary/10 animate-pulse" >
            <MicIcon className="w-20 h-20 text-primary" />
          </div>
        </div>
      </div>
    </div>
    <div className="mt-12 md:mt-24 space-y-8">
      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-bold">Recent Recordings</h2>
        <Link href="/recordings" className="text-primary hover:underline">
          View All
        </Link>
      </div>
      <Suspense>
        <Recordings />
      </Suspense>
    </div>
  </>
}

async function Recordings() {
  const { data: recordings } = await api.memo.all()

  return <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
    {recordings?.map(({ title, created_at, description }) => (
      <Card>
        <CardHeader>
          <CardTitle>{title}</CardTitle>
          <CardDescription>{created_at}</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="text-muted-foreground">
            <p>
              {description}
            </p>
          </div>
        </CardContent>
        <CardFooter>
          <Button variant="ghost" size="icon">
            <div className="w-5 h-5" />
          </Button>
          <Button variant="ghost" size="icon">
            <div className="w-5 h-5" />
          </Button>
        </CardFooter>
      </Card>
    ))}
  </div>
}

function MicIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z" />
      <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
      <line x1="12" x2="12" y1="19" y2="22" />
    </svg>
  )
}
